### ISSUE TITLE
Question about panic 'send on closed channel'

### ISSUE THREAD

**Issue by Eugentis** [spiral/broadcast-ws#2]
At one project we hit the problem with message in logs:
```
panic: send on closed channel
ee-app          | 
ee-app          | goroutine 25 [running]:
ee-app          | github.com/spiral/broadcast.(*Router).Dispatch(0xc000317580, 0xc00030ec60)
ee-app          | 	/go/pkg/mod/github.com/spiral/broadcast@v0.0.0-20191206140608-766959683e74/router.go:45 +0x219
ee-app          | github.com/spiral/broadcast-ws.newPool.func1(0xc00031ff50)
ee-app          | 	/go/pkg/mod/github.com/spiral/broadcast-ws@v1.1.2/conn_pool.go:34 +0xa3
ee-app          | created by github.com/spiral/broadcast-ws.newPool
ee-app          | 	/go/pkg/mod/github.com/spiral/broadcast-ws@v1.1.2/conn_pool.go:31 +0xea
```

Also in logs it was detected records about disconnections:
```
ee-app          | DEBU[0080] [ws] 192.168.34.3:44406 websocket: close 1001 (going away) 
ee-app          | DEBU[0080] [ws] 192.168.34.3:44406 disconnected 
```

Could you describe what should be fixe for correct work in this case?

**Comment by Eugentis** [comment]
github.com/spiral/broadcast-ws v1.1.2 used
